import { module, test } from 'qunit';
import { setupTest } from 'ember-qunit';
import { URL_REGEX } from '@upfluence/ember-upf-utils/utils/url-regex';

const VALID_URLS = [
  'toto.com',
  'toot.tooooooooaze',
  'www.totot.com',
  'www.totot.com/',
  'toto-toto.com',
  'www.toto-toto.com',
  'https://toto-toto.com',
  'http://toto-toto.com',
  'http://www.toto-toto.com',
  'https://www.toto.com',
  'sub.domain.com',
  'sub.domain.com/p',
  'sub.domain.com/paze',
  'sub.domain.com/path/azeoaize',
  'https://sub.domain.com',
  'toto-toto.com/az',
  'https://toto.com',
  'aze.te',
  'aze.t',
  'aze.te/',
  'https://aze.te',
  'https://aze.te/',
  'http://domain.com/path/sub/param&toto=true',
  'http://domain.com/path/sub/param&toto=email.john@gmail.com',
  'domain.com/path/sub/param&toto=email.john@gmail.com',
  'https://google.com',
  'www.google.com',
  'www.google.com/path/param=email@toto.com',
  'http://www.google.com/path/param=email@toto.com',
  'https://www.google.com/path/param=email@toto.com',
  'http://google.com/path/param=email@toto.com',
  'https://google.com/path/param=email@toto.com',
  'office365.com',
  'www.office365.com',
  'http://office365.com',
  'https://office365.com',
  'amazon.co.uk',
  'www.amazon.co.uk',
  'http://amazon.co.uk',
  'http://www.amazon.co.uk',
  'https://amazon.co.uk',
  'https://www.amazon.co.uk/',
  'https://mabanque.bnpparibas/',
  'https://mabanque.bnpparibas/path',
  'subdomain.example.co.uk',
  'https://subdomain.example.co.uk',
  'example.com/path?query=value',
  'example.com/path?query=value&other=123',
  'example.com#anchor',
  'example.com/path#anchor',
  'https://example.com/path#anchor',
  'https://example.com/path?q=1#anchor',
  'https://www.example.com/path?q=1#anchor',
  'https://www.example.com/path?q=1#anchor',
  'example.museum',
  'example.photography',
  'example.technology',
  'www.example.info',
  'https://example.solutions',
  'sub1.sub2.sub3.example.com',
  'a.b.c.d.e.example.com',
  '123.example.com',
  'sub123.example.com',
  'EXAMPLE.COM',
  'Example.COM',
  'WWW.EXAMPLE.COM',
  'https://EXAMPLE.COM',
  'https://WWW.EXAMPLE.COM',
  'example.com/path/to/resource',
  'example.com/path/to/resource/',
  'example.com/very/long/path/with/many/segments/here',
  'example.com/path?param1=value1&param2=value2&param3=value3',
  'example.com/path?q=search+term',
  'example.com/path?q=search%20term',
  'example.com/path/file.html',
  'example.com/path/file.pdf',
  'example.com/path/image.jpg',
  'example.com/(parentheses)',
  'example.com/path_(with)_parens',
  'example.de',
  'example.fr',
  'example.jp',
  'example.au',
  'example.ca',
  'example.cn',
  'example.io',
  'example.ai',
  'example.app',
  'https://example.dev',
  'sub-domain.example.com',
  'sub--domain.example.com',
  'a-b-c.example.com',
  'example.com/~user',
  'example.com/path_with_underscores',
  'example.com/path-with-dashes',
  'example.com/#',
  'example.com/?',
  'example.com/path?',
  'example.com/path#',
  'example.com/path?query=value#fragment',
  'www.example.com/path?query=value#fragment',
  'https://www.example.com/path?query=value#fragment'
];
const INVALID_URLS = [
  'https://toto-toto .com',
  'https://toto- toto.com',
  'https:// toto-toto.com',
  'https ://toto-toto.com',
  'aze@aze',
  'aze.aze@comaze.com',
  'aze.toto@aze',
  'https://domain@domain.com/sub/path',
  'https://domain.com /sub /path',
  'www.aze@aez.com',
  'random text goes here to make sure',
  'email@toto.com',
  'john.email@toto.com',
  'office 365.com',
  'www.office 365.com',
  'www',
  'www.upfluence',
  'word',
  'https://',
  'http://',
  'ftp://domain.com',
  '.com',
  'domain.',
  'domain..com',
  'domain-.com',
  '-domain.com',
  'domain.com.',
  'javascript:alert(1)',
  'data:text/html,<script>alert(1)</script>',
  'example.com:8080',
  'https://example.com:8080/path',
  'localhost:3000',
  '192.168.1.1',
  'http://192.168.1.1:8080',
  'example.com:80',
  'example.com:443',
  'example.com:3000',
  'http://example.com:80',
  'https://example.com:443',
  'www.example.com:8080',
  'http://www.example.com:8080',
  '10.0.0.1',
  '127.0.0.1',
  'http://10.0.0.1',
  'https://127.0.0.1',
  'http://localhost',
  'https://localhost',
  'localhost',
  '192.168.0.1:8080',
  'http://192.168.0.1/path',
  '2001:0db8:85a3:0000:0000:8a2e:0370:7334',
  'http://[2001:db8::1]',
  '255.255.255.255',
  'http://255.255.255.255:8080'
];

module('Unit | Utils | url-regex', function (hooks) {
  setupTest(hooks);

  hooks.beforeEach(function () {
    this.urlRegex = URL_REGEX;
  });

  VALID_URLS.forEach((url) => {
    test(`it should pass for ${url}`, function (assert) {
      assert.ok(this.urlRegex.test(url));
    });
  });

  INVALID_URLS.forEach((url) => {
    test(`it should not pass for ${url}`, function (assert) {
      assert.notOk(this.urlRegex.test(url));
    });
  });
});
